{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Drug Subreddit Analysis (Stage of Addiction)",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/pilot/Q7",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv", 

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/drug.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },


    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [      
        # {
        #     "annotation_type": "radio",
        #     "name": "Personal experience",
        #     "description": "Is the post describing a primary experience with a specific substance?",
        #     "labels": [
        #       { "name": "Early Use",
        #         "tooltip_file": "tooltips/Early_Use.html"
        #       },
        #       {
        #         "name": "Continued Use",
        #         "tooltip_file": "tooltips/Continued_Use.html"
        #       },

        #       { "name": "Treatment",
        #         "tooltip_file": "tooltips/Treatment.html"
        #       },
        #       "None"
        #     ],

        #     # If true, numbers [1-len(labels)] will be bound to each
        #     # label. Annotations with more than 10 are not supported with this
        #     # simple keybinding and will need to use the full item specification
        #     # to bind all labels to keys.
        #     "sequential_key_binding": True,                        
        # }, 
        {
            "annotation_type": "radio",
            "name": "Withdrawal",
            "description": "The next three questions will assess if the post is indicative of an SUD. Please see annotation guideline for the definition of an SUD. Does the post author admit to using a substance nt as prescribed?",
            "labels": [
              "Yes", "No"
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Annotations with more than 10 are not supported with this
            # simple keybinding and will need to use the full item specification
            # to bind all labels to keys.
            "sequential_key_binding": True,                        
        }, 
        {
            "annotation_type": "radio",
            "name": "Relapse",
            "description": "Does the post author admit to having a strong desire or urge to use a specified substance at least once a week or more?",
            "labels": [
              "Yes", "No"
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Annotations with more than 10 are not supported with this
            # simple keybinding and will need to use the full item specification
            # to bind all labels to keys.
            "sequential_key_binding": True,                        
        }, 
        {
            "annotation_type": "radio",
            "name": "Relapse",
            "description": "Does the post author admit to having concern about their substance use, either from themselves or from others?",
            "labels": [
              "Yes", "No"
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Annotations with more than 10 are not supported with this
            # simple keybinding and will need to use the full item specification
            # to bind all labels to keys.
            "sequential_key_binding": True,                        
        }, 
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    # you may use templates in our lib, if you want to use your own template,
    # please replace the string as a path to the template
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"

}
